### PR TITLE
Responsive Styling

### PR DESCRIPTION
**Pull request by CoryDHall**
@13milliseconds 

Is the category nav/sticky nav coming over to the new theme? and if so is that a part of bootstrap or does it need to be coded?

### CODE REVIEW

**Comment by 13milliseconds** [comment]
@CoryDHall Yes it should come over to the new site too. I don't believe it is part of Bootstrap so it should be coded.

**Comment by 13milliseconds** [comment]
@CoryDHall I saw you added a background image for thumbnails. Unfortunately we need s to be able to add alt text and for better page speed in general using srcset. I know it's no ideal but I think I found the right settings to get the images to be resized properly by moving the <a> outside of .fill.

**Comment by CoryDHall** [comment]
@13milliseconds ok thanks, /I was going to suggest not merging until everything could be resolved. because I'm seeing a lot of breaking changes on the other pages.

**Comment by CoryDHall** [comment]
@13milliseconds well, not a lot, but a few—I also think it may be a good practice to scope changes to particular pages until they can be generalized and refactored into smaller modules.

**Comment by 13milliseconds** [comment]
@CoryDHall Noted. I was worried by the inconsistent styles of the previous site so I have been trying to apply things globally but will keep changes local first.

**Pull request merged**
